import Head from "next/head";
import AboutUs from "../components/AboutUs";
import FollowBar from "../components/FollowBar";
import Navbar from "../components/Navbar";
import PointsTable from "../components/PointsTable";
import Slideshow from "../components/Slideshow";
import TopMoments from "../components/TopMoments";
import TournamentLeaders from "../components/TournamentLeaders";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>MMNCT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FollowBar />
      <Navbar />
      <div className="flex">
        <Slideshow />
        <PointsTable />
      </div>
      <TopMoments/>
      <TournamentLeaders/>
      <AboutUs/>
    </div>
  );
}
