import Head from "next/head";
<<<<<<< HEAD
import FollowBar from "../components/FollowBar";
import Navbar from "../components/Navbar";

=======
import Description from "../components/Description";
import FollowBar from "../components/FollowBar";
import Navbar from "../components/Navbar";
>>>>>>> 927a2377efec1b04d21f5224c6cd15b12b5bcc7b

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>MMNCT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FollowBar />
<<<<<<< HEAD
      <Navbar />
     
=======
      <Navbar/>
      <Description/>
>>>>>>> 927a2377efec1b04d21f5224c6cd15b12b5bcc7b
    </div>
  );
}
