import Head from "next/head";
import FollowBar from "../components/FollowBar";
import Navbar from "../components/Navbar";
function Matches() {
  return (
    <div>
      <Head>
        <title>MMNCT- Matches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FollowBar />
      <Navbar />
    </div>
  );
}

export default Matches;
